### ISSUE TITLE
Software Requirements Specification

### ISSUE THREAD

**Issue by chiefhamar** [chiefhamar/DAB_Advanced_JAVA#1]
Requires update - Due 21 June 2017 by 1300 - Assigned to Daniel Hamar - Input from remainder of team in class.

**Comment by chiefhamar** [comment]
Alright guys, this is the updated System Requirements file.  Please read through it carefully and let me know any changes or issues.  You will notice a paragraph highlighted yellow.  This is an area that I don't know enough about and hopefully you guys can tell me what it should say.  Other than that, enjoy.

[Escape the Third - Software Requirements Specification v1-0.docx](https://github.com/chiefhamar/DAB_Advanced_JAVA/files/1089062/Escape.the.Third.-.Software.Requirements.Specification.v1-0.docx)

**Comment by Trazel-Apeally** [comment]
From what I know, the highlighted bit seems fine enough, though 80mb may get chewed up by the Narration depending on how long it is, however, we should be fine.

**Comment by DaemonRizing** [comment]
The sound files will definitely eat up the 80mb. It won't only be the narration it will also be the background music and any sounds we include for interaction with the environment. The rest of the highlighted area does seem fine to me.

**Comment by chiefhamar** [comment]
Alright.  Tomorrow we can come up with a better guess for the size.  I have some programs to work with sound here, but I don't think it will compress it that much.  Thanks for the input, see ya in the morning.



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by chiefhamar** [comment]
We received a 100% on our submission.  Closing this issue.
