### ISSUE TITLE
UML Diagram and Storyboards

### ISSUE THREAD

**Issue by chiefhamar** [chiefhamar/DAB_Advanced_JAVA#2]
Use UML (use case and interactive) to diagram the design of the system structure and behavior of the game; storyboards for the user interface design of the system (due: June 26th by 1pm – submitted by project leader).

**Comment by Trazel-Apeally** [comment]
Here's the first draft of the Use case, let me know if there is anything that y'all think should be included before I move onto the Class Diagram

![use case v1](https://user-images.githubusercontent.com/15951036/27358971-1a213118-55e7-11e7-8332-6752e16afc8e.PNG)

**Comment by DaemonRizing** [comment]
that seems pretty solid for a use case. I don't think anything is missing
to represent the functionality of it.

**Comment by Trazel-Apeally** [comment]
I originally had howToPlayButton() named helpButton(), but didn't like how it sounded. If helpButton() fits better, I'll go ahead and use that instead, maybe add in some generalizations for it as well

**Comment by Trazel-Apeally** [comment]
Use case revision 1, final use case WILL be different than all other versions, but this should be the one we'll submit for Monday.

![use case v2](https://user-images.githubusercontent.com/15951036/27396761-169c9258-5682-11e7-9831-9723ebd76f7e.PNG)

**Comment by DaemonRizing** [comment]
![storyboardhelpmenu](https://user-images.githubusercontent.com/29434717/27549094-f4bc5a8e-5a68-11e7-9b93-e0f015165c64.PNG)
![storyboardhouseover](https://user-images.githubusercontent.com/29434717/27549097-f4c0c79a-5a68-11e7-9401-0cc6b23a6dd3.PNG)
![storyboardmenu](https://user-images.githubusercontent.com/29434717/27549096-f4bfda2e-5a68-11e7-9d0b-97d09d7a0d7f.PNG)
![storyboardnarrative](https://user-images.githubusercontent.com/29434717/27549095-f4bcfbd8-5a68-11e7-891c-21d4b43ba296.PNG)
![storyboardoverview](https://user-images.githubusercontent.com/29434717/27549101-f4c67802-5a68-11e7-8f1b-a5844ad9e6b4.PNG)
![storyboardoverview_end](https://user-images.githubusercontent.com/29434717/27549098-f4c1dbe4-5a68-11e7-86e1-220d64ab02cd.PNG)
![storyboardquestion](https://user-images.githubusercontent.com/29434717/27549099-f4c38174-5a68-11e7-88a6-28c32826e089.PNG)
![storyboardroomover](https://user-images.githubusercontent.com/29434717/27549100-f4c3ee70-5a68-11e7-9cde-a8e0342623ae.PNG)
![storyboardwin](https://user-images.githubusercontent.com/29434717/27549103-f4e68a66-5a68-11e7-883c-d255126a947d.PNG)

**Comment by chiefhamar** [comment]
Comments on our Use Case and Storyboard - Grade 95
"Very good interactivity diagram as well as the use case.  The only thing missing from the use case is a system actor.  The storyboard is good, but looking for the name of the game."
"Storyboard would be more effective by using similar graphics for game and color, but I did get an idea of what you will be creating."
